### PR TITLE
Add better testabilitiy

### PR DESCRIPTION
**Pull request by TheMeinerLP**
## Description
Allows us to fix some stuff faster and improves our workflow

```[tasklist]
### Submitter Checklist
- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

**Review by SirYwell — COMMENTED** [review]
Server files should be added to the .gitignore

**Comment by NotMyFault** [comment]
Does any of the people working on FAVS use this? I don't.

**Comment by TheMeinerLP** [comment]
I use it and I'm currently on it to fix that bug what I have found and before I push stuff that's not the bug related I opened this PR

**Comment by Aurelien30000** [comment]
I don’t because I prefer my specific server setup but that’s still a good idea.

**Comment by TheMeinerLP** [comment]
> I don’t because I prefer my specific server setup but that’s still a good idea.

Thanks for that feedback 😄

**Review by NotMyFault — CHANGES_REQUESTED** [review]
The change proposed in insufficient. FAVS specifies a hard dependency on FAWE, invoking the runServer task will never launch a test server to try FAVS builds on.

**Comment by TheMeinerLP** [comment]
> The change proposed in insufficient. FAVS specifies a hard dependency on FAWE, invoking the runServer task will never launch a test server to try FAVS builds on.

You mean when i start Run Server task. The FAVS build will never be triggerd ?

**Comment by NotMyFault** [comment]
> > The change proposed in insufficient. FAVS specifies a hard dependency on FAWE, invoking the runServer task will never launch a test server to try FAVS builds on.
> 
> You mean when i start Run Server task. The FAVS build will never be triggerd ?

FAVS can't launch without having FAWE installed.

**Comment by TheMeinerLP** [comment]
> > > The change proposed in insufficient. FAVS specifies a hard dependency on FAWE, invoking the runServer task will never launch a test server to try FAVS builds on.
> > 
> > 
> > You mean when i start Run Server task. The FAVS build will never be triggerd ?
> 
> FAVS can't launch without having FAWE installed.

Same behavior on PSv6/7

**Comment by NotMyFault** [comment]
Different topic, which should be updated or removed then.

**Comment by TheMeinerLP** [comment]
> Different topic, which should be updated or removed then.

I try to add a option or a way to autodownload FAWE from ci

**Comment by NotMyFault** [comment]
I'm going ahead and close this PR to comply with https://github.com/IntellectualSites/PlotSquared/commit/9dff20f96caeb9f94f73ae19c834796e108f3bfb

**Pull request closed without merging**
