### PR TITLE
Feature/1.17.1

### PR DESCRIPTION
**Pull request by NotMyFault**

### CODE REVIEW

**Comment by NotMyFault** [comment]
@Aurelien30000 Do you also want to take a look at https://github.com/IntellectualSites/FastAsyncVoxelSniper/issues/8? You don't have to if you don't want to, you did already a good job at Favs, but letting me know allows me to coordinate this merge a bit better.

**Comment by Aurelien30000** [comment]
Surely, should be easy to re-add!

**Comment by NotMyFault** [comment]
Tested with Fawe version 1.17-49 on Paper build 99 (1.17.1) it appears I occasionally experience lighting issues:
/b eb & /b 5

Edit: Since we're using Fawe to process edits (?) this may need to be addressed there or handled differently here.

**Comment by Aurelien30000** [comment]
A bit strange, I didn't experience any problem during my tests and progress (on Tuinity).
Note: Voxel itself doesn't interact with lighting.

**Comment by NotMyFault** [comment]
Tuinity: https://streamable.com/xsilwh
Paper: https://streamable.com/s07khr

Since Fawe utilizes Starlight, I guess we handle things different here. However,  using Tuinity I have have a shadow blink on every every edit. Not for a long time, but quite noticeable on the video linked. On Paper I didn't experience them so far but constant shadows occurring occasionally thru edits.
But on the other hand, I didn't experience (at least visually) shadow blinks on Paper.

<blockquote><div>Streamable</div><div><strong><a href="https://streamable.com/xsilwh">2021-07-11 13-54-21</a></strong></div><div>Watch "2021-07-11 13-54-21" on Streamable.</div></blockquote>
<blockquote><div>Streamable</div><div><strong><a href="https://streamable.com/s07khr">2021-07-11 13-55-42</a></strong></div><div>Watch "2021-07-11 13-55-42" on Streamable.</div></blockquote>

**Comment by Aurelien30000** [comment]
Humm, interesting, doesn't it seem to be a client visual issue? If you log out and then log again, do the shadows still appear?

**Comment by NotMyFault** [comment]
> Humm, interesting, doesn't it seem to be a client visual issue? If you log out and then log again, do the shadows still appear?

Packets are resend by then so no. They only affect the current login session.

**Comment by Aurelien30000** [comment]
Hey again, tried FAVS wih friends, and it seems that the problem is directly related to FAWE.
Use a brush such as ``//brush sphere air 5``, and apply the brush multiple times until issue occurs. So this issue seems related to the implementation of the light engine for spigot/paper.
image

**Comment by NotMyFault** [comment]
I've lazily risen an issue on the appropriate repository handling described behavior.

**Comment by NotMyFault** [comment]
I drafted a release a bit earlier, since the main functionalities appear to work. However, I found a bunch of other issues after testing all brushes (very tedious):
- [ ] Named light issues above
- [x] `/b regenerate_chunk` applying on a chunk you previously selected via `//chunk` -> `//set 0` solely sends the message without regening the chunk.
- [ ] https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1180
- [x] `/v` only recognizing material names, not block tags like `//set ##logs` or others -> https://github.com/IntellectualSites/FastAsyncVoxelSniper/pull/37/commits/b22b3a2db25a3f2b37521ff8bf290005946b8300
- [x] `/vc` failing if no input is provided -> https://github.com/IntellectualSites/FastAsyncVoxelSniper/pull/37/commits/b22b3a2db25a3f2b37521ff8bf290005946b8300
- [x] `/goto` failing if no input is provided -> https://github.com/IntellectualSites/FastAsyncVoxelSniper/pull/37/commits/b22b3a2db25a3f2b37521ff8bf290005946b8300

**Comment by Aurelien30000** [comment]
> * [ ]  `/b regenerate_chunk` applying on a chunk you previously selected via `//chunk` -> `//set 0` solely sends the message without regening the chunk.

About this one, do you mean an _empty_ chunk doesn't regenerate as expected, with full terrain?

**Comment by NotMyFault** [comment]
> > * [ ]   `/b regenerate_chunk` applying on a chunk you previously selected via `//chunk` -> `//set 0` solely sends the message without regening the chunk.
> 
> About this one, do you mean an _empty_ chunk doesn't regenerate as expected, with full terrain?

Yes.

**Pull request merged**
