### PR TITLE
Replace url with uri

### LINKED ISSUE #307: Address deprecated URL instantiation
Starting with Java 20, instantiating URLs via `new URL` is deprecated in favor of `URI#toURL()`.

While the project's codebase targets Java 17, we can address backwards-compatible deprecations still.

The file of concern is the following: https://github.com/search?q=repo%3AIntellectualSites%2Ffastasyncvoxelsniper%20%22new%20URL%22&type=code

More information about the deprecation can be found in the [javadocs](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/net/URL.html#%3Cinit%3E(java.net.URL,java.lang.String)) and [constructor deprecation](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/net/URL.html#constructor-deprecation).

### PR DESCRIPTION
**Pull request by TheMeinerLP**
## Overview
Replace deprecated code. Happy Hacktoberfest
Fixes #307

## Description

```[tasklist]
### Submitter Checklist
- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

**Comment by NotMyFault** [comment]
PRs created before October may not count in all counters.

**Comment by TheMeinerLP** [comment]
Can we wait ?

**Comment by NotMyFault** [comment]
> Can we wait ?

I don't think they'll count PRs created before October.

**Comment by BlockyTheDev** [comment]
> > Can we wait ?
> 
> I don't think they'll count PRs created before October.

Hacktoberfest website - "Pull/Merge Request Details":
```
[out-of-bounds] Your PR/MRs must be within the bounds of Hacktoberfest.

Your PR/MRs must be created between October 1 and October 31 (in any time zone, UTC-12 thru UTC+14).

Your PR/MRs must be made to a public, unarchived repository.
```

**Comment by NotMyFault** [comment]
I'll close this PR for now, feel free to resubmit it during October :)

**Pull request closed without merging**
